services:
  api:
    platform: linux/amd64
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20.12.0
    ports:
      - "3000:3000"
      - "9223:9223"
    volumes:
      - ./.cache:/app/.cache
    networks:
      - steel-network

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://api:3000
      - VITE_WS_URL=ws://api:3000
      - VITE_OPENAPI_URL=http://api:3000/documentation/json
    depends_on:
      - api
    networks:
      - steel-network

networks:
  steel-network:
    driver: bridge
